### ISSUE TITLE
Setup eslint lsp server

### ISSUE THREAD

**Issue by jdsprink91** [jdsprink91/sprinkle-nvim#5]
I think I just have to make sure the eslint lsp is installed and then I might be good to go.

Something I should do to make sure this is working is:

1. Remove prettier and eslint things from null-ls
2. Make sure eslint servier is installed via mason
3. Set it up in `lsp.lua`

**Comment by sprinkle-literati** [comment]
Still had to leave prettier in null-ls because we aren't running prettier via eslint. I guess we could if we wanted.
