### ISSUE TITLE
Explor python text objects

### ISSUE THREAD

**Issue by sprinkle-literati** [jdsprink91/sprinkle-nvim#6]
I want a better way to say something like "delete all the code in this function". More languages are based around something besides an indent (curly braces, parens). What would it be like to find a pythonic way of representing something like this?

**Comment by jdsprink91** [comment]
Potentially use treesitter to help out with this one: https://github.com/nvim-treesitter/nvim-treesitter-textobjects

**Comment by sprinkle-literati** [comment]
ALSO DID THIS THING
